import type { Metadata } from "next";
import "./globals.css";
import QueryProvider from "./components/QueryProvider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en">
      <body className="min-h-full flex flex-col">
        <QueryProvider>
          {/* fixed 사이드바(w-56)와 겹치지 않도록 본문 시작 위치 확보 + flex 자식 폭 축소 */}
          <div className="flex-1 min-w-0 w-full pl-56">{children}</div>
        </QueryProvider>
      </body>
    </html>
  );
}
